#!/bin/sh
set -e
# Automatically added by dh_installinit/11.3.5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/squeezelite" ]; then
		update-rc.d squeezelite defaults >/dev/null
		invoke-rc.d squeezelite start || exit 1
	fi
fi
# End automatically added section
