#!/bin/sh

set -e

umask 0022
ACTION="$1"
VERSION="$2"

if [ "$ACTION" = "configure" ]; then
    # add the squeezelite user
    if ! getent passwd squeezelite >/dev/null; then
        adduser --quiet --ingroup audio --system --no-create-home --shell /usr/sbin/nologin squeezelite
    fi
fi

if [ "$ACTION" = "configure" ] || [ "$ACTION" = "abort-upgrade" ] || [ "$ACTION" = "abort-deconfigure" ] || [ "$ACTION" = "abort-remove" ] ; then
        if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true

               	# This will only remove masks created by d-s-h on package removal.
		deb-systemd-helper unmask 'squeezelite.service' >/dev/null || true

	        # was-enabled defaults to true, so new installations run enable.
        	if deb-systemd-helper --quiet was-enabled 'squeezelite.service' ; then
                	# Enables the unit on first installation, creates new
	                # symlinks on upgrades if the unit file has changed.
	                deb-systemd-helper enable 'squeezelite.service' >/dev/null || true
	        else
	                # Update the statefile to add new symlinks (if any), which need to be
	                # cleaned up on purge. Also remove old symlinks.
	                deb-systemd-helper update-state 'squeezelite.service' >/dev/null || true
	        fi

                if [ -n "$VERSION" ]; then
                        _dh_action=restart
                else
                        _dh_action=start
                fi
                deb-systemd-invoke $_dh_action 'squeezelite.service' >/dev/null || true
        fi
fi
