#!/bin/sh

set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'squeezelite.service' >/dev/null || true
fi

if [ -x "/etc/init.d/squeezelite" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native squeezelite stop || exit 1
fi

